Repository sergiodxa/remix-auth, pull requests merged in 2021-12, with the labels that each got.

#74 Remove unused import from README.md
  README.md
Labels: documentation

#73 Fix small errors in KCD docs
  docs/strategies/kcd.md
Labels: documentation

#71 Create Discord Strategy
  docs/strategies/discord.md
  src/strategies/discord.ts
  src/strategies/index.ts
  test/strategies/discord.test.ts
Labels: strategy

#78 Adds Auth0Strategy example.
  examples/auth0/.env.example
  examples/auth0/.gitignore
  examples/auth0/README.md
  examples/auth0/app/entry.client.tsx
  examples/auth0/app/entry.server.tsx
  examples/auth0/app/models/user.ts
  examples/auth0/app/root.tsx
  examples/auth0/app/routes/auth/callback.tsx
  examples/auth0/app/routes/auth/login.tsx
  examples/auth0/app/routes/auth/logout.tsx
  examples/auth0/app/routes/index.tsx
  examples/auth0/app/services/auth.server.ts
  examples/auth0/app/services/session.server.ts
  examples/auth0/app/styles/global.css
  examples/auth0/app/styles/index.css
  examples/auth0/package.json
  examples/auth0/public/favicon.png
  examples/auth0/remix.config.js
  examples/auth0/remix.env.d.ts
  examples/auth0/tsconfig.json
Labels: documentation

#80 fix the bug in the github callback of example app.
  examples/github/app/routes/auth.github.callback.tsx
Labels: documentation

#81 add User-Agent to GitHub strategy
  src/strategies/github.ts
Labels: bug

#82 add User-Agent to GitHub strategy
  src/strategies/github.ts
Labels: bug

#84 Fix KCD example to await `isAuthenticated` to fix crashes due to unhandled promises
  docs/strategies/kcd.md
Labels: documentation

#75 Pass errors thrown from local strategy in an object with a message property
  src/strategies/local.ts
  test/strategies/local.test.ts
Labels: bug

#89 docs: (fix) typos
  docs/authenticator.md
  docs/strategies/kcd.md
  src/authenticator.ts
  src/strategies/kcd.ts
  src/strategies/oauth2.ts
Labels: documentation

#86 Use webcrypto when node crypto is not supported
  .prettierrc.js
  package.json
  src/lib/crypto.browser.ts
  src/lib/crypto.ts
  src/strategies/kcd.ts
Labels: bug

#93 Refactor crypto implementation for KCDStrategy, fix linter and tests
  package.json
  src/crypto/browser.ts
  src/crypto/index.ts
  src/crypto/types.ts
  src/lib/crypto.browser.ts
  src/lib/crypto.ts
  src/strategies/kcd.ts
  src/strategies/local.ts
  test/strategies/kcd.test.ts
Labels: enhancement

#101 Version 3
  package-lock.json
  package.json
  src/authenticator.ts
  src/authorizer.ts
  src/error.ts
  src/index.ts
  src/strategies/auth0.ts
  src/strategies/basic.ts
  src/strategies/custom.ts
  src/strategies/discord.ts
  src/strategies/github.ts
  src/strategies/google.ts
  src/strategies/index.ts
  src/strategies/kcd.ts
  src/strategies/local.ts
  src/strategies/mock.ts
  src/strategies/oauth2.ts
  src/strategies/shopify.ts
  src/strategy.ts
  test/authenticator.test.ts
  test/strategies/auth0.test.ts
  test/strategies/basic.test.ts
  test/strategies/custom.test.ts
  test/strategies/discord.test.ts
  test/strategies/github.test.ts
  test/strategies/google.test.ts
  test/strategies/kcd.test.ts
  test/strategies/local.test.ts
  test/strategies/oauth2.test.ts
  test/strategies/shopify.test.ts
  tsconfig.json
Labels: breaking change

#110 Remove strategies already published in other packages
  package.json
  src/crypto/browser.ts
  src/crypto/index.ts
  src/crypto/types.ts
  src/strategies/auth0.ts
  src/strategies/discord.ts
  src/strategies/github.ts
  src/strategies/google.ts
  src/strategies/index.ts
  src/strategies/kcd.ts
  src/strategies/local.ts
  src/strategies/oauth2.ts
  test/strategies/auth0.test.ts
  test/strategies/discord.test.ts
  test/strategies/github.test.ts
  test/strategies/google.test.ts
  test/strategies/kcd.test.ts
  test/strategies/local.test.ts
  test/strategies/oauth2.test.ts
Labels: enhancement

#112 Update the documentation for v3
  README.md
Labels: documentation

#113 Add AppLoadContext as a strategy and authenticate option
  src/authenticator.ts
  src/strategy.ts
Labels: enhancement
