Repository sergiodxa/remix-auth, pull requests merged in 2021-11, with the labels that each got.

#38 Upgrade Remix support to v0.20
  package-lock.json
  package.json
Labels: enhancement

#41 Create Shopify strategy
  src/strategies/shopify.ts
Labels: strategy

#42 Add ShopifyStrategy tests
  docs/strategies/shopify.md
  src/strategies/index.ts
  src/strategies/shopify.ts
  test/strategies/shopify.test.ts
Labels: enhancement

#53 Upgrade Remix packages to 0.21.0
  package-lock.json
  package.json
Labels: enhancement

#51 Set @remix-run/server-runtime as peerDependencies instead of @remix-run/node
  .github/workflows/main.yml
  package-lock.json
  package.json
  src/authenticator.ts
  src/strategies/basic.ts
  src/strategies/custom.ts
  src/strategies/kcd.ts
  src/strategies/local.ts
  src/strategies/oauth2.ts
  test/authenticator.test.ts
  test/strategies/auth0.test.ts
  test/strategies/custom.test.ts
  test/strategies/github.test.ts
  test/strategies/google.test.ts
  test/strategies/kcd.test.ts
  test/strategies/local.test.ts
  test/strategies/oauth2.test.ts
  test/strategies/shopify.test.ts
Labels: enhancement

#54 Switch from esbuild to tsc
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#60 Fix examples not returning a Promise in actions
  README.md
  docs/strategies/github.md
  docs/strategies/google.md
Labels: dependencies

#56 Use UUID instead of randomBytes from Node crypto
  package-lock.json
  package.json
  src/strategies/oauth2.ts
Labels: enhancement

#65 Upgrade to Remix v1
  .github/workflows/bump.yml
  .github/workflows/main.yml
  .github/workflows/publish.yml
  .npmrc
  examples/github/app/root.tsx
  examples/github/app/routes/index.tsx
  examples/github/package.json
  examples/local/app/root.tsx
  examples/local/app/routes/index.tsx
  examples/local/package.json
  package-lock.json
  package.json
  remix.env.d.ts
  tsconfig.json
Labels: enhancement

#67 Authorization
  package-lock.json
  package.json
  src/authorizer.ts
  src/index.ts
  test/authorizers.test.ts
Labels: enhancement

#70 Update google documentation
  docs/strategies/google.md
Labels: documentation
