Repository sergiodxa/remix-auth, pull requests merged in 2022-09, with the labels that each got.

#189 Super small fix to docs
  README.md
Labels: documentation

#190 Accept session in addition to request
  src/authenticator.ts
  src/strategy.ts
Labels: enhancement

#192 Fix custom strategy name not being set in session
  src/authenticator.ts
  src/strategy.ts
  test/authenticator.test.ts
Labels: bug

#196 Use `ActionArgs`/`LoaderArgs` instead of `ActionFunction`/`LoaderFunction`
  README.md
  docs/authenticator.md
  src/authenticator.ts
Labels: documentation
