Repository sergiodxa/remix-auth, pull requests merged in 2022-01, with the labels that each got.

#117 Set the strategy name in session after success with redirect
  src/authenticator.ts
  src/strategy.ts
  test/authenticator.test.ts
Labels: enhancement

#118 Add logout method to the authenticator
  README.md
  src/authenticator.ts
  test/authenticator.test.ts
Labels: enhancement

#119 Ensure sessionSomething properties in Authenticator are not typed as undefined
  src/authenticator.ts
Labels: bug

#120 Fix: `README.md` typo
  README.md
Labels: documentation

#121 Fix a small test typo
  test/authenticator.test.ts
Labels: documentation
